export const ERROR_CODES = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  TAX_CALCULATION_ERROR: "TAX_CALCULATION_ERROR",
  API_ERROR: "API_ERROR",
  NOT_FOUND: "NOT_FOUND",
  UNAUTHORIZED: "UNAUTHORIZED",
  RATE_LIMITED: "RATE_LIMITED",
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
